# Generated by Django 4.2.3 on 2023-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ipaddress_article_htis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='htis',
            new_name='hits',
        ),
    ]
